# K-Means Modeling 

To see patterns in the data, I decided K-means models were the best way to see how countries are grouped as far as Chinese aid and other factors. Below are several K-means models, with different variables. I also tried DBSCAN models, but got negative silhouette scores, so decided to stay with the K-means models for this data.

In [1128]:
# Importing libraries 
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [1129]:
# Reading in the combined aid data 
aid = pd.read_csv('./aid_data/combined_data/aid_sums.csv')

In [1130]:
# Looking at my data frame 
aid.head()

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_00,hdi_14,pr_score00,cl_score00,fh_status00,pr_score14,...,resource_rents,gdp_per_cap00,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max
0,Algeria,4.380505e+08,5.880901e+08,2.476621e+08,0.646,0.749,6.0,5.0,NF,6.0,...,24.602722,1764.888222,7.673,0.0,2937.203478,0.103,11.254086,15.108798,6.362761,1
1,Angola,8.030873e+08,3.864233e+10,2.939893e+09,0.394,0.557,6.0,6.0,NF,6.0,...,23.381930,556.836318,40.676,-1.0,3286.361923,0.163,29.808251,1434.290317,109.120217,1
2,Benin,1.107820e+09,1.155924e+09,1.785451e+09,0.398,0.505,2.0,2.0,F,2.0,...,4.872945,374.192394,30.452,0.0,460.251202,0.107,107.692898,112.369168,173.566471,0
3,Botswana,3.858719e+08,2.563158e+09,2.141447e+09,0.578,0.709,2.0,2.0,F,3.0,...,2.516289,3522.308678,17.346,1.0,4341.944603,0.131,184.750231,1227.205008,1025.295634,1
4,Burkina Faso,2.858288e+09,0.000000e+00,2.048434e+09,0.286,0.405,4.0,4.0,PF,6.0,...,16.981603,226.475981,30.387,1.0,413.232114,0.119,162.531851,0.000000,116.480855,0

In [1131]:
# Looking at my columns 
print(aid.columns)

Index(['country', 'world_bank_totals', 'chinese_aid_totals', 'usaid_aid',
       'hdi_00', 'hdi_14', 'pr_score00', 'cl_score00', 'fh_status00',
       'pr_score14', 'cl_score14', 'fh_status14', 'cpi_2014', 'population',
       'gdp_per_cap14', 'resource_rents', 'gdp_per_cap00', 'debt_to_gdp',
       'fh_change', 'pc_gdp_change', 'hdi_change', 'world_bank_pc',
       'chinese_aid_pc', 'usaid_pc', 'chinese_aid_total_max'],
      dtype='object')

## K-means Model with All Numeric Features

In [1132]:
# Scaling my features, for this one putting almost all the variables into the model 
ss = StandardScaler()
X_scaled = ss.fit_transform(aid[['world_bank_totals', 'chinese_aid_totals', 'usaid_aid',
       'hdi_00', 'hdi_14', 'pr_score00', 'cl_score00', 
       'pr_score14', 'cl_score14', 'cpi_2014', 'population',
       'gdp_per_cap14', 'resource_rents', 'gdp_per_cap00', 'debt_to_gdp',
       'fh_change', 'pc_gdp_change', 'hdi_change', 'world_bank_pc',
       'chinese_aid_pc', 'usaid_pc']])

In [1133]:
# Instantiating my k-means model. True K of 9 gave me the best silhouette score. 
true_k = 9
model = KMeans(n_clusters=true_k, init='k-means++', max_iter=100, n_init=1, random_state=22)
model.fit(X_scaled)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=100,
       n_clusters=9, n_init=1, n_jobs=None, precompute_distances='auto',
       random_state=22, tol=0.0001, verbose=0)

In [1134]:
# Predicting my clusters 
model.predict(X_scaled)

array([6, 0, 1, 1, 0, 0, 1, 0, 4, 4, 0, 4, 0, 0, 0, 0, 4, 3, 6, 4, 1, 0,
       4, 6, 8, 4, 0, 0, 0, 0, 0, 0, 0, 4, 1, 0, 0, 1, 0, 3, 0, 1, 1, 0,
       1, 4, 0, 0, 0, 0, 0, 0, 4, 0, 5, 6, 7, 6, 0, 4, 4, 4, 5, 4, 5, 6,
       2, 6], dtype=int32)

In [1135]:
# Making a column for the labels for this model and taking a look at it 
aid['clusters_all'] = model.labels_
aid.head()

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_00,hdi_14,pr_score00,cl_score00,fh_status00,pr_score14,...,gdp_per_cap00,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all
0,Algeria,4.380505e+08,5.880901e+08,2.476621e+08,0.646,0.749,6.0,5.0,NF,6.0,...,1764.888222,7.673,0.0,2937.203478,0.103,11.254086,15.108798,6.362761,1,6
1,Angola,8.030873e+08,3.864233e+10,2.939893e+09,0.394,0.557,6.0,6.0,NF,6.0,...,556.836318,40.676,-1.0,3286.361923,0.163,29.808251,1434.290317,109.120217,1,0
2,Benin,1.107820e+09,1.155924e+09,1.785451e+09,0.398,0.505,2.0,2.0,F,2.0,...,374.192394,30.452,0.0,460.251202,0.107,107.692898,112.369168,173.566471,0,1
3,Botswana,3.858719e+08,2.563158e+09,2.141447e+09,0.578,0.709,2.0,2.0,F,3.0,...,3522.308678,17.346,1.0,4341.944603,0.131,184.750231,1227.205008,1025.295634,1,1
4,Burkina Faso,2.858288e+09,0.000000e+00,2.048434e+09,0.286,0.405,4.0,4.0,PF,6.0,...,226.475981,30.387,1.0,413.232114,0.119,162.531851,0.000000,116.480855,0,0

In [1136]:
# This silhouette score is just okay
silhouette_score(X_scaled, model.labels_)

0.12292105001931611

In [1137]:
# Value counts for each of these clusters 
aid['clusters_all'].value_counts()

0    30
4    14
1     9
6     7
5     3
3     2
8     1
7     1
2     1
Name: clusters_all, dtype: int64

In [1138]:
# Making a dataframe for the statistics of cluster 4 
cluster_4 = aid[aid['clusters_all'] == 4].describe().T

In [1139]:
# Looking at this data frame 
cluster_4.head()

,count,mean,std,min,25%,50%,75%,max
world_bank_totals,14.0,5.221058e+08,7.340143e+08,0.000000e+00,3.158422e+07,2.453035e+08,5.168319e+08,2.445064e+09
chinese_aid_totals,14.0,4.842222e+09,9.763207e+09,0.000000e+00,1.632687e+08,3.943970e+08,1.447106e+09,3.061064e+10
usaid_aid,14.0,5.095573e+09,7.711530e+09,1.392312e+08,5.829387e+08,2.912450e+09,4.178440e+09,2.581800e+10
hdi_00,14.0,4.520923e-01,1.137448e-01,2.980000e-01,3.872500e-01,4.490000e-01,5.074306e-01,7.020000e-01
hdi_14,14.0,4.894286e-01,9.342600e-02,3.550000e-01,4.352500e-01,4.730000e-01,5.322500e-01,7.200000e-01

In [1140]:
# Only keeping the mean column 
cluster_4 = cluster_4['mean']

In [1141]:
# Making a dataframe for cluster 0 
cluster_0 = aid[aid['clusters_all'] == 0].describe().T

In [1142]:
# Keeping only the mean column 
cluster_0 = cluster_0['mean']

In [1143]:
# Making this series into a dataframe 
cluster_4 = pd.DataFrame(cluster_4)

In [1144]:
# Making this series into a dataframe 
cluster_0 = pd.DataFrame(cluster_0)

In [1145]:
# Looking at the cluster 0 data frame 
cluster_0.head()

                            mean
world_bank_totals   3.173744e+09
chinese_aid_totals  5.753771e+09
usaid_aid           5.901221e+09
hdi_00              4.169620e-01
hdi_14              5.284333e-01

In [1146]:
# Renaming the column to mean_0
cluster_0.rename(columns={'mean': "mean_0"}, inplace=True)

In [1147]:
# Renaming the column to mean_4
cluster_4.rename(columns={'mean': "mean_4"}, inplace=True)

In [1148]:
# Combining the data frames 
cluster_compare = cluster_0.join(cluster_4)

In [1149]:
# Making a column of the difference between the two 
cluster_compare['cluster_difference'] = cluster_compare['mean_0'] - cluster_compare['mean_4']

In [1150]:
cluster_compare.head(25)

                             mean_0        mean_4  cluster_difference
world_bank_totals      3.173744e+09  5.221058e+08        2.651638e+09
chinese_aid_totals     5.753771e+09  4.842222e+09        9.115488e+08
usaid_aid              5.901221e+09  5.095573e+09        8.056478e+08
hdi_00                 4.169620e-01  4.520923e-01       -3.513022e-02
hdi_14                 5.284333e-01  4.894286e-01        3.900476e-02
pr_score00             5.033333e+00  5.785714e+00       -7.523810e-01
cl_score00             4.800000e+00  5.428571e+00       -6.285714e-01
pr_score14             4.500000e+00  6.357143e+00       -1.857143e+00
cl_score14             4.300000e+00  6.142857e+00       -1.842857e+00
cpi_2014               3.241667e+01  2.200000e+01        1.041667e+01
population             2.312248e+07  1.171351e+07        1.140898e+07
gdp_per_cap14          1.983004e+03  1.399207e+03        5.837968e+02
resource_rents         1.143373e+01  1.661579e+01       -5.182066e+00
gdp_per_cap00          8.459149e+02  1.202949e+03       -3.570339e+02
debt_to_gdp            4.101953e+01  6.289364e+01       -2.187411e+01
fh_change             -1.033333e+00  1.285714e+00       -2.319048e+00
pc_gdp_change          1.137089e+03  1.962584e+02        9.408308e+02
hdi_change             1.114713e-01  3.733631e-02        7.413499e-02
world_bank_pc          1.302052e+02  6.948966e+01        6.071552e+01
chinese_aid_pc         2.352938e+02  3.775749e+02       -1.422811e+02
usaid_pc               3.690459e+02  4.132214e+02       -4.417550e+01
chinese_aid_total_max  3.666667e-01  3.571429e-01        9.523810e-03
clusters_all           0.000000e+00  4.000000e+00       -4.000000e+00

### Some characteristics of cluster 0, the largest cluster (compared to cluster 4, the second largest): 

- More total aid from China, US, and World Bank
- Lower Freedom House scores (which is good)
- Higher CPI (also good)
- Higher populations
- Lower percentage of gdp from resources
- Lower debt to gdp 
- Improving freedom house scores
- Larger changes in HDI
- More per capita world bank aid, lower per capita Chinese and US aid

In [1151]:
aid[aid['clusters_all'] == 0]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_00,hdi_14,pr_score00,cl_score00,fh_status00,pr_score14,...,gdp_per_cap00,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all
1,Angola,8.030873e+08,3.864233e+10,2.939893e+09,0.394000,0.557,6.0,6.0,NF,6.0,...,556.836318,40.676,-1.0,3286.361923,0.163000,29.808251,1434.290317,109.120217,1,0
4,Burkina Faso,2.858288e+09,0.000000e+00,2.048434e+09,0.286000,0.405,4.0,4.0,PF,6.0,...,226.475981,30.387,1.0,413.232114,0.119000,162.531851,0.000000,116.480855,0,0
5,Burundi,1.163282e+09,5.582052e+08,1.500181e+09,0.293000,0.429,6.0,6.0,NF,6.0,...,136.463971,35.772,-1.0,108.862768,0.136000,118.168117,56.703409,152.390909,0,0
7,Cameroon,1.324141e+09,1.342278e+10,6.346854e+08,0.439000,0.540,7.0,6.0,NF,6.0,...,649.991845,21.534,-1.0,750.395172,0.101000,58.378848,591.784862,27.982074,1,0
10,Comoros,7.368316e+07,2.803613e+08,1.124295e+07,0.457000,0.534,6.0,4.0,PF,3.0,...,645.818691,22.597,-3.0,723.357940,0.077000,97.029399,369.192814,14.805236,1,0
12,Cote D'Ivoire,1.815460e+09,2.865090e+09,1.851870e+09,0.407000,0.478,6.0,5.0,PF,5.0,...,651.305907,44.790,-2.0,726.490656,0.071000,80.160942,126.506998,81.768633,1,0
13,Democratic Republic of Congo,5.359333e+09,1.356688e+09,6.982450e+09,0.333000,0.441,7.0,6.0,NF,6.0,...,405.216253,17.510,-1.0,-7.874582,0.108000,72.651738,18.391425,94.654899,0,0
14,Djibouti,1.897235e+08,7.788110e+07,4.741077e+08,0.361000,0.475,4.0,5.0,PF,6.0,...,768.176077,38.811,2.0,826.973923,0.114000,211.109741,86.660117,527.550675,0,0
15,Egypt,8.205844e+09,6.151464e+08,6.129272e+10,0.611000,0.683,6.0,5.0,NF,6.0,...,1450.476242,85.127,0.0,1197.817927,0.072000,90.747858,6.802861,677.831989,0,0
21,Guinea,6.315845e+08,9.247885e+08,1.347825e+09,0.335000,0.446,6.0,5.0,NF,5.0,...,363.482479,35.090,-1.0,377.555656,0.111000,56.639386,82.933402,120.870534,0,0
26,Kenya,5.346269e+09,3.953264e+10,1.513368e+10,0.446000,0.556,6.0,5.0,NF,4.0,...,397.482659,48.564,-3.0,662.612357,0.110000,114.481181,846.523638,324.061835,1,0
27,Lebanon,1.388968e+09,6.290871e+07,4.989869e+09,0.507431,0.732,6.0,5.0,NF,5.0,...,4491.637259,139.158,-2.0,2157.576513,0.224569,221.794562,10.045447,796.796976,0,0
28,Lesotho,3.305411e+08,2.453521e+08,1.388199e+09,0.444000,0.493,4.0,4.0,PF,2.0,...,436.488352,36.801,-3.0,953.387180,0.049000,161.757413,120.068365,679.345187,0,0
29,Liberia,9.805636e+08,6.930387e+08,4.512835e+09,0.422000,0.464,5.0,6.0,PF,3.0,...,306.832895,21.632,-4.0,279.396466,0.042000,224.925436,158.971888,1035.171491,0,0
30,Madagascar,2.249696e+09,1.650177e+08,2.095127e+09,0.456000,0.512,2.0,4.0,PF,4.0,...,245.939066,34.651,2.0,222.173935,0.056000,95.366966,6.995274,88.814640,0,0
31,Malawi,1.771178e+09,1.028785e+09,4.089349e+09,0.362000,0.472,3.0,3.0,PF,3.0,...,156.385719,55.240,1.0,351.152256,0.110000,108.731015,63.156175,251.041411,0,0
32,Mali,2.152685e+09,1.876385e+09,4.318933e+09,0.308000,0.414,2.0,3.0,F,5.0,...,269.871138,27.277,4.0,437.110416,0.106000,127.120385,110.804309,255.041747,0,0
35,Morocco,5.975941e+09,6.318299e+09,3.366876e+09,0.531000,0.653,5.0,4.0,PF,5.0,...,1334.943051,63.339,0.0,1790.136430,0.122000,174.774221,184.786931,98.468710,1,0
36,Mozambique,3.848939e+09,7.052097e+09,8.185871e+09,0.301000,0.420,3.0,4.0,PF,4.0,...,313.568034,62.371,0.0,244.641310,0.119000,146.424544,268.281734,311.413708,0,0
38,Niger,1.594254e+09,1.783428e+09,1.784885e+09,0.253000,0.353,4.0,4.0,PF,3.0,...,158.704975,31.976,-1.0,226.195681,0.100000,82.860756,92.693030,92.768755,0,0
40,Rwanda,2.101319e+09,3.305603e+09,3.652478e+09,0.337000,0.513,7.0,6.0,NF,6.0,...,218.680163,29.131,-1.0,469.532036,0.176000,189.587494,298.241806,329.537887,0,0
43,Sierra Leone,7.927226e+08,1.421289e+09,1.099909e+09,0.298000,0.430,4.0,5.0,PF,3.0,...,138.698692,34.966,-3.0,429.135575,0.132000,112.969412,202.545202,156.746025,1,0
46,Swaziland,4.690000e+07,0.000000e+00,5.409131e+08,0.468000,0.573,6.0,5.0,NF,7.0,...,1728.705335,14.279,1.0,2849.583235,0.105000,42.830229,0.000000,493.975048,0,0
47,Tanzania,7.763594e+09,2.410282e+10,9.664759e+09,0.395000,0.509,4.0,4.0,PF,3.0,...,410.952328,33.795,-2.0,435.434514,0.114000,155.396745,482.444055,193.450622,1,0
48,Togo,4.326932e+08,4.314954e+09,1.472300e+08,0.426000,0.495,5.0,5.0,PF,4.0,...,302.206394,60.447,-2.0,309.328675,0.069000,60.618296,604.504844,20.626228,1,0
49,Tunisia,3.714659e+09,1.355463e+08,1.054239e+09,0.653000,0.728,6.0,5.0,NF,1.0,...,2211.826817,51.561,-7.0,2090.659727,0.075000,335.767137,12.251993,95.292374,0,0
50,Turkey,2.560656e+10,8.767650e+09,1.776648e+09,0.655000,0.792,4.0,5.0,PF,3.0,...,4316.548908,28.769,-2.0,8961.211862,0.137000,331.554180,113.523680,23.004070,1,0
51,Uganda,5.086029e+09,3.755668e+09,1.032902e+10,0.395000,0.509,6.0,5.0,PF,6.0,...,261.868998,30.798,0.0,414.468635,0.114000,137.787414,101.746117,279.827034,0,0
53,Zambia,1.604376e+09,9.288269e+09,6.452866e+09,0.428000,0.565,5.0,4.0,PF,3.0,...,345.689554,36.137,-2.0,1298.417236,0.137000,104.181955,603.144023,419.024020,1,0
58,Palestine,0.000000e+00,2.011175e+07,1.336954e+10,0.507431,0.682,6.0,6.0,NF,6.0,...,1476.171850,17.400,0.0,1127.349164,0.174569,0.000000,4.819035,3203.513553,0,0

In [1152]:
# Many of these countries appear to be troubled and poor, without making as much progress as those in 
# cluster 0
aid[aid['clusters_all'] == 4]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_00,hdi_14,pr_score00,cl_score00,fh_status00,pr_score14,...,gdp_per_cap00,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all
8,Central African Republic,2.945852e+08,3.967369e+08,5.523907e+08,0.307000,0.355,3.0,4.0,PF,7.0,...,251.206877,69.162,7.0,82.907673,0.048000,65.988710,88.871262,123.738588,0,4
9,Chad,7.629853e+08,1.522646e+09,2.885400e+09,0.298000,0.406,6.0,5.0,NF,7.0,...,165.762987,41.545,2.0,794.677933,0.108000,55.840891,111.438466,211.174845,0,4
11,Congo,4.820413e+08,9.013684e+09,2.433887e+08,0.495000,0.595,6.0,4.0,PF,6.0,...,1029.577037,47.605,1.0,1976.159875,0.100000,101.761441,1902.835892,51.380637,1,4
16,Eritrea,4.860429e+08,4.853948e+08,1.028387e+09,0.507431,0.436,7.0,5.0,NF,7.0,...,308.133784,128.674,2.0,158.866216,-0.071431,108.612937,108.468120,229.807076,0,4
19,Gambia,1.598891e+08,0.000000e+00,1.392312e+08,0.382000,0.449,7.0,5.0,NF,6.0,...,594.151643,104.889,0.0,153.557089,0.067000,78.994956,0.000000,68.788680,0,4
22,Guinea-Bissau,1.960218e+08,3.091138e+08,1.520517e+08,0.507431,0.450,4.0,5.0,PF,5.0,...,308.144119,54.856,1.0,247.460929,-0.057431,115.822072,182.643988,89.841749,1,4
25,Jordan,1.829419e+09,1.578224e+08,2.581800e+10,0.702000,0.720,4.0,4.0,PF,6.0,...,1674.825261,89.049,3.0,1678.798121,0.018000,205.090735,17.692999,2894.378653,0,4
33,Mauritania,5.270949e+08,1.220488e+09,6.745826e+08,0.446000,0.518,6.0,5.0,NF,6.0,...,491.842762,80.361,0.0,877.345183,0.072000,134.090267,310.485915,171.610380,1,4
45,South Sudan,1.263369e+08,1.391514e+08,4.261786e+09,0.507431,0.435,7.0,7.0,NF,7.0,...,9171.330145,38.339,0.0,-8339.479683,-0.072431,11.969520,13.183603,403.773891,0,4
52,Yemen,2.445064e+09,3.920571e+08,2.939501e+09,0.432000,0.504,5.0,6.0,NF,6.0,...,554.448633,48.722,1.0,564.698860,0.072000,94.683749,15.182190,113.830522,0,4
59,Somalia,0.000000e+00,2.630742e+07,5.911542e+09,0.300000,0.400,6.0,7.0,NF,7.0,...,185.000000,41.690,1.0,301.080000,0.100000,0.000000,1.959792,440.385023,0,4
60,Sudan,0.000000e+00,3.061064e+10,1.923096e+10,0.403000,0.496,7.0,7.0,NF,7.0,...,366.172808,56.005,0.0,1459.368229,0.093000,0.000000,806.017098,506.375568,1,4
61,Syria,0.000000e+00,1.796076e+08,3.572409e+09,0.590000,0.551,7.0,7.0,NF,7.0,...,1177.629268,30.010,0.0,2122.370732,-0.039000,0.000000,9.596641,190.877966,0,4
63,Zimbabwe,0.000000e+00,2.333746e+10,3.928401e+09,0.452000,0.537,6.0,5.0,PF,5.0,...,563.057741,49.604,0.0,669.807124,0.085000,0.000000,1717.672202,289.136213,1,4

In [1153]:
# These countries are fairly prosperous and democratic compared to clusters 0 and 4 
aid[aid['clusters_all'] == 1]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_00,hdi_14,pr_score00,cl_score00,fh_status00,pr_score14,...,gdp_per_cap00,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all
2,Benin,1.107820e+09,1.155924e+09,1.785451e+09,0.398,0.505,2.0,2.0,F,2.0,...,374.192394,30.452,0.0,460.251202,0.107,107.692898,112.369168,173.566471,0,1
3,Botswana,3.858719e+08,2.563158e+09,2.141447e+09,0.578,0.709,2.0,2.0,F,3.0,...,3522.308678,17.346,1.0,4341.944603,0.131,184.750231,1227.205008,1025.295634,1,1
6,Cabo Verde,2.794196e+08,2.061266e+08,5.275526e+08,0.564,0.641,1.0,2.0,F,1.0,...,1259.323656,115.924,-1.0,2163.425146,0.077,539.140106,397.721329,1017.912719,0,1
20,Ghana,4.853869e+09,1.266398e+10,4.463691e+09,0.483,0.577,2.0,3.0,F,1.0,...,258.470959,70.157,-2.0,1368.151823,0.094,178.290666,465.168975,163.958789,1,1
34,Mauritius,4.383398e+08,1.848213e+10,2.438720e+07,0.674,0.786,1.0,2.0,F,1.0,...,3929.075495,57.543,0.0,5234.557978,0.112,347.631028,14657.494792,19.340582,1,1
37,Namibia,1.583345e+07,2.942054e+09,2.659016e+09,0.543,0.631,2.0,3.0,F,2.0,...,2136.440243,25.189,-1.0,4018.048643,0.088,6.964562,1294.103684,1169.605220,1,1
41,Sao Tome and Principe,5.515899e+07,0.000000e+00,3.884767e+07,0.480,0.577,1.0,2.0,F,2.0,...,1062.490000,69.553,1.0,150.674082,0.097,281.815956,0.000000,198.478856,0,1
42,Senegal,2.227930e+09,2.037594e+09,3.656034e+09,0.390,0.501,3.0,4.0,PF,2.0,...,604.654066,54.462,-3.0,732.752624,0.111,157.176179,143.748325,257.926176,0,1
44,South Africa,3.848384e+09,3.355333e+09,1.058959e+10,0.629,0.691,1.0,2.0,F,2.0,...,3032.427138,46.985,1.0,4550.269791,0.062,70.553013,61.513827,194.140619,0,1

In [1154]:
# Qatar is an outlier in some senses. Does not receive much aid, high hdi, high gdp, authoritarian country
aid[aid['clusters_all'] == 2]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_00,hdi_14,pr_score00,cl_score00,fh_status00,pr_score14,...,gdp_per_cap00,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all
66,Qatar,0.0,0.0,18859773.0,0.816,0.854,6.0,6.0,NF,6.0,...,29976.11704,24.912,-1.0,35584.25836,0.038,0.0,0.0,7.669075,0,2

In [1155]:
# These are populous nations that receive lots of aid, particularly from China. They are partially-free
# according to Freedom House, and are in the middle as far as HDI. 
aid[aid['clusters_all'] == 3]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_00,hdi_14,pr_score00,cl_score00,fh_status00,pr_score14,...,gdp_per_cap00,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all
17,Ethiopia,1.145084e+10,8.330864e+10,1.901191e+10,0.283000,0.446,5.0,5.0,PF,6.0,...,124.460800,46.802,2.0,324.959577,0.163000,116.733003,849.271394,193.812700,1,3
39,Nigeria,1.075609e+10,3.251860e+10,9.655779e+09,0.507431,0.523,4.0,4.0,PF,4.0,...,567.930736,13.072,1.0,1995.969233,0.015569,60.973878,184.340680,54.736455,1,3

In [1156]:
# Oil rich, non-democratic nations with high HDI
aid[aid['clusters_all'] == 5]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_00,hdi_14,pr_score00,cl_score00,fh_status00,pr_score14,...,gdp_per_cap00,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all
54,Bahrain,0.0,18159502.92,900204738.0,0.792,0.810,7.0,6.0,NF,7.0,...,13636.39623,44.397,0.0,8758.90980,0.018,0.0,13.591679,673.768118,0,5
62,United Arab Emirates,0.0,31771063.00,37945421.0,0.782,0.847,6.0,5.0,NF,6.0,...,33291.41937,15.537,1.0,5203.62698,0.065,0.0,3.448064,4.118157,0,5
64,Kuwait,0.0,0.00,8617661.0,0.786,0.800,4.0,5.0,PF,5.0,...,18440.37852,3.429,1.0,18718.35568,0.014,0.0,0.000000,2.334813,0,5

In [1157]:
# Mostly non-democratic Arab countries, with fairly high HDI
aid[aid['clusters_all'] == 6]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_00,hdi_14,pr_score00,cl_score00,fh_status00,pr_score14,...,gdp_per_cap00,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all
0,Algeria,4.380505e+08,5.880901e+08,247662135.0,0.646,0.749,6.0,5.0,NF,6.0,...,1764.888222,7.673,0.0,2937.203478,0.103,11.254086,15.108798,6.362761,1,6
18,Gabon,6.245637e+07,2.036791e+09,100394128.0,0.627,0.688,5.0,4.0,PF,6.0,...,4125.716664,34.063,2.0,5341.647122,0.061,33.154461,1081.213802,53.293411,1,6
23,Iran,1.605363e+09,0.000000e+00,63865441.0,0.671,0.788,6.0,6.0,NF,6.0,...,1670.009470,11.826,0.0,4566.279941,0.117,20.723515,0.000000,0.824435,0,6
55,Equatorial Guinea,0.000000e+00,3.762500e+09,5080444.0,0.520,0.590,7.0,7.0,NF,7.0,...,1725.554738,12.721,0.0,14404.781632,0.070,0.000000,3352.562039,4.526911,1,6
57,Libya,0.000000e+00,1.730100e+07,950008484.0,0.728,0.693,7.0,7.0,NF,6.0,...,7142.774452,36.390,-2.0,-611.917737,-0.035,0.000000,2.719413,149.324577,0,6
65,Oman,0.000000e+00,0.000000e+00,885517811.0,0.704,0.815,6.0,5.0,NF,6.0,...,8601.254170,4.925,0.0,8283.029240,0.111,0.000000,0.000000,219.880964,0,6
67,Saudi Arabia,0.000000e+00,0.000000e+00,20942632.0,0.744,0.853,7.0,7.0,NF,7.0,...,9171.330145,1.562,0.0,11916.024265,0.109,0.000000,0.000000,0.677383,0,6

In [1158]:
# Democratic country with very high US aid, high HDI
aid[aid['clusters_all'] == 7]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_00,hdi_14,pr_score00,cl_score00,fh_status00,pr_score14,...,gdp_per_cap00,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all
56,Israel,0.0,6.623150e+07,1.020541e+11,0.853,0.9,1.0,3.0,F,1.0,...,21043.57493,66.094,-1.0,11934.38594,0.047,0.0,8.061577,12421.83908,0,7

In [1159]:
# Non-democratic, oil-rich country which has received massive amounts of US aid 
aid[aid['clusters_all'] == 8]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_00,hdi_14,pr_score00,cl_score00,fh_status00,pr_score14,...,gdp_per_cap00,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all
24,Iraq,1.174182e+09,2.349945e+07,1.343100e+11,0.608,0.662,7.0,7.0,NF,6.0,...,1100.0,32.028,-2.0,4244.331964,0.054,34.121353,0.682886,3903.0044,0,8

## Removing Some Columns

This will allow me to look at the data more easily for the rest of the models. I am getting rid of the 2000 columns since those were mostly to calculate the different between variables.

In [1160]:
print(aid.columns)

Index(['country', 'world_bank_totals', 'chinese_aid_totals', 'usaid_aid',
       'hdi_00', 'hdi_14', 'pr_score00', 'cl_score00', 'fh_status00',
       'pr_score14', 'cl_score14', 'fh_status14', 'cpi_2014', 'population',
       'gdp_per_cap14', 'resource_rents', 'gdp_per_cap00', 'debt_to_gdp',
       'fh_change', 'pc_gdp_change', 'hdi_change', 'world_bank_pc',
       'chinese_aid_pc', 'usaid_pc', 'chinese_aid_total_max', 'clusters_all'],
      dtype='object')

In [1161]:
aid = aid[['country', 'world_bank_totals', 'chinese_aid_totals', 'usaid_aid', 'hdi_14', 'pr_score14', 'cl_score14', 'fh_status14', 'cpi_2014', 'gdp_per_cap14', 'resource_rents', 'debt_to_gdp',
       'fh_change', 'pc_gdp_change', 'hdi_change', 'world_bank_pc',
       'chinese_aid_pc', 'usaid_pc', 'chinese_aid_total_max', 'clusters_all']]

In [1162]:
aid.head()

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,resource_rents,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all
0,Algeria,4.380505e+08,5.880901e+08,2.476621e+08,0.749,6.0,5.0,NF,36.0,4702.091700,24.602722,7.673,0.0,2937.203478,0.103,11.254086,15.108798,6.362761,1,6
1,Angola,8.030873e+08,3.864233e+10,2.939893e+09,0.557,6.0,5.0,NF,19.0,3843.198241,23.381930,40.676,-1.0,3286.361923,0.163,29.808251,1434.290317,109.120217,1,0
2,Benin,1.107820e+09,1.155924e+09,1.785451e+09,0.505,2.0,2.0,F,39.0,834.443596,4.872945,30.452,0.0,460.251202,0.107,107.692898,112.369168,173.566471,0,1
3,Botswana,3.858719e+08,2.563158e+09,2.141447e+09,0.709,3.0,2.0,F,63.0,7864.253281,2.516289,17.346,1.0,4341.944603,0.131,184.750231,1227.205008,1025.295634,1,1
4,Burkina Faso,2.858288e+09,0.000000e+00,2.048434e+09,0.405,6.0,3.0,PF,38.0,639.708096,16.981603,30.387,1.0,413.232114,0.119,162.531851,0.000000,116.480855,0,0

## K-means Model with Aid Totals

In [1163]:
# Scaling, fitting and transforming my features
ss = StandardScaler()
X_scaled2 = ss.fit_transform(aid[['world_bank_totals', 'chinese_aid_totals', 'usaid_aid']])

In [1164]:
# Instantiating my model. 4 clusters gave me the best silhouette score. 
true_k = 4
model = KMeans(n_clusters=true_k, init='k-means++', max_iter=100, n_init=1, random_state=22)
model.fit(X_scaled2)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=100,
       n_clusters=4, n_init=1, n_jobs=None, precompute_distances='auto',
       random_state=22, tol=0.0001, verbose=0)

In [1165]:
# Making predictions 
model.predict(X_scaled2)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 3, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0], dtype=int32)

In [1166]:
# Making a column for the labels for this model 
aid['cluster_all_aid'] = model.labels_
aid.head()

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid
0,Algeria,4.380505e+08,5.880901e+08,2.476621e+08,0.749,6.0,5.0,NF,36.0,4702.091700,...,7.673,0.0,2937.203478,0.103,11.254086,15.108798,6.362761,1,6,0
1,Angola,8.030873e+08,3.864233e+10,2.939893e+09,0.557,6.0,5.0,NF,19.0,3843.198241,...,40.676,-1.0,3286.361923,0.163,29.808251,1434.290317,109.120217,1,0,1
2,Benin,1.107820e+09,1.155924e+09,1.785451e+09,0.505,2.0,2.0,F,39.0,834.443596,...,30.452,0.0,460.251202,0.107,107.692898,112.369168,173.566471,0,1,0
3,Botswana,3.858719e+08,2.563158e+09,2.141447e+09,0.709,3.0,2.0,F,63.0,7864.253281,...,17.346,1.0,4341.944603,0.131,184.750231,1227.205008,1025.295634,1,1,0
4,Burkina Faso,2.858288e+09,0.000000e+00,2.048434e+09,0.405,6.0,3.0,PF,38.0,639.708096,...,30.387,1.0,413.232114,0.119,162.531851,0.000000,116.480855,0,0,0

In [1167]:
# Checking the silouhette score for this model, which is good
silhouette_score(X_scaled2, model.labels_)

0.7143082216474426

In [1168]:
# Looking at the value counts. The majority fall in one cluster 
aid['cluster_all_aid'].value_counts()

0    59
1     6
2     2
3     1
Name: cluster_all_aid, dtype: int64

In [1169]:
# These are highly populous countries that mostly receive a lot of aid in general. 
aid[aid['cluster_all_aid'] == 1]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid
1,Angola,8.030873e+08,3.864233e+10,2.939893e+09,0.557,6.0,5.0,NF,19.0,3843.198241,...,40.676,-1.0,3286.361923,0.163000,29.808251,1434.290317,109.120217,1,0,1
17,Ethiopia,1.145084e+10,8.330864e+10,1.901191e+10,0.446,6.0,6.0,NF,33.0,449.420377,...,46.802,2.0,324.959577,0.163000,116.733003,849.271394,193.812700,1,3,1
26,Kenya,5.346269e+09,3.953264e+10,1.513368e+10,0.556,4.0,4.0,PF,25.0,1060.095016,...,48.564,-3.0,662.612357,0.110000,114.481181,846.523638,324.061835,1,0,1
39,Nigeria,1.075609e+10,3.251860e+10,9.655779e+09,0.523,4.0,5.0,PF,27.0,2563.899969,...,13.072,1.0,1995.969233,0.015569,60.973878,184.340680,54.736455,1,3,1
47,Tanzania,7.763594e+09,2.410282e+10,9.664759e+09,0.509,3.0,3.0,PF,31.0,846.386841,...,33.795,-2.0,435.434514,0.114000,155.396745,482.444055,193.450622,1,0,1
60,Sudan,0.000000e+00,3.061064e+10,1.923096e+10,0.496,7.0,7.0,NF,11.0,1825.541037,...,56.005,0.0,1459.368229,0.093000,0.000000,806.017098,506.375568,1,4,1

In [1170]:
# Two countries that recieve massive amounts of US aid 
aid[aid['cluster_all_aid'] == 2]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid
24,Iraq,1.174182e+09,2.349945e+07,1.343100e+11,0.662,6.0,6.0,NF,16.0,5344.331964,...,32.028,-2.0,4244.331964,0.054,34.121353,0.682886,3903.00440,0,8,2
56,Israel,0.000000e+00,6.623150e+07,1.020541e+11,0.900,1.0,2.0,F,60.0,32977.960870,...,66.094,-1.0,11934.385940,0.047,0.000000,8.061577,12421.83908,0,7,2

In [1171]:
# Receives more total World Bank aid than any other country 
aid[aid['cluster_all_aid'] == 3]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,debt_to_gdp,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid
50,Turkey,2.560656e+10,8.767650e+09,1.776648e+09,0.792,3.0,4.0,PF,45.0,13277.76077,...,28.769,-2.0,8961.211862,0.137,331.55418,113.52368,23.00407,1,0,3

## K-means Model with Per Capita Aid

In [1172]:
# Scaling features for aid per capita 
ss = StandardScaler()
X_scaled3 = ss.fit_transform(aid[['chinese_aid_pc', 'world_bank_pc', 'usaid_pc']])

In [1173]:
# Instantiating my model. true_k=5 gave me the best silouhette score 
true_k = 5
model = KMeans(n_clusters=true_k, init='k-means++', max_iter=100, n_init=1, random_state=22)
model.fit(X_scaled3)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=100,
       n_clusters=5, n_init=1, n_jobs=None, precompute_distances='auto',
       random_state=22, tol=0.0001, verbose=0)

In [1174]:
# Using my model to make predictions
model.predict(X_scaled3)

array([0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 4, 4, 0, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int32)

In [1175]:
# Making a column for new clusters
aid['cluster_pc_aid'] = model.labels_
aid.head()

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid,cluster_pc_aid
0,Algeria,4.380505e+08,5.880901e+08,2.476621e+08,0.749,6.0,5.0,NF,36.0,4702.091700,...,0.0,2937.203478,0.103,11.254086,15.108798,6.362761,1,6,0,0
1,Angola,8.030873e+08,3.864233e+10,2.939893e+09,0.557,6.0,5.0,NF,19.0,3843.198241,...,-1.0,3286.361923,0.163,29.808251,1434.290317,109.120217,1,0,1,0
2,Benin,1.107820e+09,1.155924e+09,1.785451e+09,0.505,2.0,2.0,F,39.0,834.443596,...,0.0,460.251202,0.107,107.692898,112.369168,173.566471,0,1,0,0
3,Botswana,3.858719e+08,2.563158e+09,2.141447e+09,0.709,3.0,2.0,F,63.0,7864.253281,...,1.0,4341.944603,0.131,184.750231,1227.205008,1025.295634,1,1,0,0
4,Burkina Faso,2.858288e+09,0.000000e+00,2.048434e+09,0.405,6.0,3.0,PF,38.0,639.708096,...,1.0,413.232114,0.119,162.531851,0.000000,116.480855,0,0,0,0

In [1176]:
# Checking my silhouette score, which is good
silhouette_score(X_scaled3, model.labels_)

0.52561342959283

In [1177]:
# Most of the countries are in the same cluster
aid['cluster_pc_aid'].value_counts()

0    56
2     7
4     3
3     1
1     1
Name: cluster_pc_aid, dtype: int64

In [1178]:
# Mauritius gets a huge amount of aid per capita, as it is a small country 
aid[aid['cluster_pc_aid'] == 1]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid,cluster_pc_aid
34,Mauritius,4.383398e+08,1.848213e+10,24387198.0,0.786,1.0,2.0,F,54.0,9163.633473,...,0.0,5234.557978,0.112,347.631028,14657.494792,19.340582,1,1,0,1

In [1179]:
# Mostly get more US aid
aid[aid['cluster_pc_aid'] == 2]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid,cluster_pc_aid
6,Cabo Verde,2.794196e+08,2.061266e+08,5.275526e+08,0.641,1.0,1.0,F,57.0,3422.748802,...,-1.0,2163.425146,0.077000,539.140106,397.721329,1017.912719,0,1,0,2
14,Djibouti,1.897235e+08,7.788110e+07,4.741077e+08,0.475,6.0,5.0,NF,34.0,1595.150000,...,2.0,826.973923,0.114000,211.109741,86.660117,527.550675,0,0,0,2
27,Lebanon,1.388968e+09,6.290871e+07,4.989869e+09,0.732,5.0,4.0,PF,27.0,6649.213772,...,-2.0,2157.576513,0.224569,221.794562,10.045447,796.796976,0,0,0,2
29,Liberia,9.805636e+08,6.930387e+08,4.512835e+09,0.464,3.0,4.0,PF,37.0,586.229361,...,-4.0,279.396466,0.042000,224.925436,158.971888,1035.171491,0,0,0,2
41,Sao Tome and Principe,5.515899e+07,0.000000e+00,3.884767e+07,0.577,2.0,2.0,F,42.0,1213.164082,...,1.0,150.674082,0.097000,281.815956,0.000000,198.478856,0,1,0,2
49,Tunisia,3.714659e+09,1.355463e+08,1.054239e+09,0.728,1.0,3.0,F,40.0,4302.486544,...,-7.0,2090.659727,0.075000,335.767137,12.251993,95.292374,0,0,0,2
50,Turkey,2.560656e+10,8.767650e+09,1.776648e+09,0.792,3.0,4.0,PF,45.0,13277.760770,...,-2.0,8961.211862,0.137000,331.554180,113.523680,23.004070,1,0,3,2

In [1180]:
# Receives a ton of aid per capita from the United States
aid[aid['cluster_pc_aid'] == 3]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid,cluster_pc_aid
56,Israel,0.0,6.623150e+07,1.020541e+11,0.9,1.0,2.0,F,60.0,32977.96087,...,-1.0,11934.38594,0.047,0.0,8.061577,12421.83908,0,7,2,3

In [1181]:
# Arab countries receiving a lot of US aid per capita 
aid[aid['cluster_pc_aid'] == 4]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,fh_change,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid,cluster_pc_aid
24,Iraq,1.174182e+09,2.349945e+07,1.343100e+11,0.662,6.0,6.0,NF,16.0,5344.331964,...,-2.0,4244.331964,0.054000,34.121353,0.682886,3903.004400,0,8,2,4
25,Jordan,1.829419e+09,1.578224e+08,2.581800e+10,0.720,6.0,5.0,NF,49.0,3353.623382,...,3.0,1678.798121,0.018000,205.090735,17.692999,2894.378653,0,4,0,4
58,Palestine,0.000000e+00,2.011175e+07,1.336954e+10,0.682,6.0,6.0,NF,24.5,2603.521014,...,0.0,1127.349164,0.174569,0.000000,4.819035,3203.513553,0,0,0,4

## K-Means with Selected Features

This is a simplified version of the first K-Means model, with only Chinese aid total, 2014 variables, and the changes from 2000 to 2014.

In [1182]:
# Scaling my features
ss = StandardScaler()
X_scaled4 = ss.fit_transform(aid[['chinese_aid_totals', 'hdi_14','pr_score14', 'cl_score14', 'cpi_2014',
       'gdp_per_cap14', 'resource_rents', 'debt_to_gdp','fh_change', 'pc_gdp_change', 'hdi_change', 
       'chinese_aid_pc']])

In [1183]:
# Instantiating my model. true_k=3 gave me the best silouhette score 
true_k = 3
model = KMeans(n_clusters=true_k, init='k-means++', max_iter=100, n_init=1, random_state=22)
model.fit(X_scaled4)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=100,
       n_clusters=3, n_init=1, n_jobs=None, precompute_distances='auto',
       random_state=22, tol=0.0001, verbose=0)

In [1184]:
# Using my model to make predictions
model.predict(X_scaled4)

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1], dtype=int32)

In [1185]:
# Making a column for new clusters
aid['clusters_selected_features'] = model.labels_
aid.head()

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid,cluster_pc_aid,clusters_selected_features
0,Algeria,4.380505e+08,5.880901e+08,2.476621e+08,0.749,6.0,5.0,NF,36.0,4702.091700,...,2937.203478,0.103,11.254086,15.108798,6.362761,1,6,0,0,1
1,Angola,8.030873e+08,3.864233e+10,2.939893e+09,0.557,6.0,5.0,NF,19.0,3843.198241,...,3286.361923,0.163,29.808251,1434.290317,109.120217,1,0,1,0,0
2,Benin,1.107820e+09,1.155924e+09,1.785451e+09,0.505,2.0,2.0,F,39.0,834.443596,...,460.251202,0.107,107.692898,112.369168,173.566471,0,1,0,0,0
3,Botswana,3.858719e+08,2.563158e+09,2.141447e+09,0.709,3.0,2.0,F,63.0,7864.253281,...,4341.944603,0.131,184.750231,1227.205008,1025.295634,1,1,0,0,0
4,Burkina Faso,2.858288e+09,0.000000e+00,2.048434e+09,0.405,6.0,3.0,PF,38.0,639.708096,...,413.232114,0.119,162.531851,0.000000,116.480855,0,0,0,0,0

In [1186]:
# Checking my silhouette score, which is alright 
silhouette_score(X_scaled4, model.labels_)

0.2532277457745736

In [1187]:
# Checking my value counts
aid['clusters_selected_features'].value_counts()

0    54
1    13
2     1
Name: clusters_selected_features, dtype: int64

In [1188]:
# Making a data frame of the description of cluster 0
cluster_0 = aid[aid['clusters_selected_features'] == 0].describe().T

In [1189]:
# Keeping just the mean
cluster_0 = cluster_0['mean']

In [1190]:
# Making a data frame of the description of cluster 1
cluster_1 = aid[aid['clusters_selected_features'] == 1].describe().T

In [1191]:
# Keeping just the mean
cluster_1 = cluster_1['mean']

In [1192]:
# Looking at the head of the data
cluster_0.head()

world_bank_totals     2.546352e+09
chinese_aid_totals    7.058438e+09
usaid_aid             5.609333e+09
hdi_14                5.278889e-01
pr_score14            4.611111e+00
Name: mean, dtype: float64

In [1193]:
# Putting the cluster in a data frame
cluster_0 = cluster_0.to_frame()

In [1194]:
# Renaming the column
cluster_0.rename(columns={'mean': 'means_0'}, inplace=True)

In [1195]:
# Saving cluster 1 to a data frame
cluster_1 = cluster_1.to_frame()

In [1196]:
# Renaming my columns 
cluster_1.rename(columns={'mean': 'means_1'}, inplace=True)

In [1197]:
# Joining my data frames
cluster_compare = cluster_0.join(cluster_1)

In [1198]:
# Checking to see if this worked
cluster_compare.head()

                         means_0       means_1
world_bank_totals   2.546352e+09  2.523117e+08
chinese_aid_totals  7.058438e+09  5.034110e+08
usaid_aid           5.609333e+09  1.843102e+10
hdi_14              5.278889e-01  7.730000e-01
pr_score14          4.611111e+00  5.769231e+00

In [1199]:
# Making a column for the difference between the two 
cluster_compare['difference'] = cluster_compare['means_0'] - cluster_compare['means_1']

In [1200]:
# Looking at my values 
cluster_compare.head(25)

                                 means_0       means_1    difference
world_bank_totals           2.546352e+09  2.523117e+08  2.294040e+09
chinese_aid_totals          7.058438e+09  5.034110e+08  6.555027e+09
usaid_aid                   5.609333e+09  1.843102e+10 -1.282168e+10
hdi_14                      5.278889e-01  7.730000e-01 -2.451111e-01
pr_score14                  4.611111e+00  5.769231e+00 -1.158120e+00
cl_score14                  4.462963e+00  5.461538e+00 -9.985755e-01
cpi_2014                    3.195370e+01  4.138462e+01 -9.430912e+00
gdp_per_cap14               2.076448e+03  2.176695e+04 -1.969050e+04
resource_rents              1.178241e+01  3.056750e+01 -1.878509e+01
debt_to_gdp                 4.816739e+01  2.273515e+01  2.543224e+01
fh_change                  -2.592593e-01 -1.538462e-01 -1.054131e-01
pc_gdp_change               1.054940e+03  1.009853e+04 -9.043592e+03
hdi_change                  8.911883e-02  5.938462e-02  2.973421e-02
world_bank_pc               1.219093e+02  7.634878e+00  1.142744e+02
chinese_aid_pc              3.163019e+02  3.444145e+02 -2.811255e+01
usaid_pc                    3.945539e+02  1.342125e+03 -9.475710e+02
chinese_aid_total_max       3.888889e-01  2.307692e-01  1.581197e-01
clusters_all                1.296296e+00  5.692308e+00 -4.396011e+00
cluster_all_aid             1.666667e-01  3.076923e-01 -1.410256e-01
cluster_pc_aid              4.074074e-01  5.384615e-01 -1.310541e-01
clusters_selected_features  0.000000e+00  1.000000e+00 -1.000000e+00

### Some characteristics of cluster 0, the largest cluster (compared to cluster 1, the second largest): 

- Higher total average aid from World Bank and China, but less from the United States
- Lower HDI
- Lower Freedom House scores (which is good) and more of a positive trend
- More corrupt 
- Lower GDP per capita
- Less of GDP from resource rents
- Higher debt to GDP
- Larger jump in HDI
- More per capita World Bank aid, slightly less per capita from China, less per capita US aid

In [1201]:
# Looking at the lone country in cluster 2 
aid[aid['clusters_selected_features'] == 2]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid,cluster_pc_aid,clusters_selected_features
34,Mauritius,4.383398e+08,1.848213e+10,24387198.0,0.786,1.0,2.0,F,54.0,9163.633473,...,5234.557978,0.112,347.631028,14657.494792,19.340582,1,1,0,1,2

In [1202]:
# Looking the countries in cluster 0
aid[aid['clusters_selected_features'] == 0]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid,cluster_pc_aid,clusters_selected_features
1,Angola,8.030873e+08,3.864233e+10,2.939893e+09,0.557,6.0,5.0,NF,19.0,3843.198241,...,3286.361923,0.163000,29.808251,1434.290317,109.120217,1,0,1,0,0
2,Benin,1.107820e+09,1.155924e+09,1.785451e+09,0.505,2.0,2.0,F,39.0,834.443596,...,460.251202,0.107000,107.692898,112.369168,173.566471,0,1,0,0,0
3,Botswana,3.858719e+08,2.563158e+09,2.141447e+09,0.709,3.0,2.0,F,63.0,7864.253281,...,4341.944603,0.131000,184.750231,1227.205008,1025.295634,1,1,0,0,0
4,Burkina Faso,2.858288e+09,0.000000e+00,2.048434e+09,0.405,6.0,3.0,PF,38.0,639.708096,...,413.232114,0.119000,162.531851,0.000000,116.480855,0,0,0,0,0
5,Burundi,1.163282e+09,5.582052e+08,1.500181e+09,0.429,6.0,5.0,NF,20.0,245.326739,...,108.862768,0.136000,118.168117,56.703409,152.390909,0,0,0,0,0
6,Cabo Verde,2.794196e+08,2.061266e+08,5.275526e+08,0.641,1.0,1.0,F,57.0,3422.748802,...,2163.425146,0.077000,539.140106,397.721329,1017.912719,0,1,0,2,0
7,Cameroon,1.324141e+09,1.342278e+10,6.346854e+08,0.540,6.0,6.0,NF,27.0,1400.387017,...,750.395172,0.101000,58.378848,591.784862,27.982074,1,0,0,0,0
8,Central African Republic,2.945852e+08,3.967369e+08,5.523907e+08,0.355,7.0,7.0,NF,24.0,334.114551,...,82.907673,0.048000,65.988710,88.871262,123.738588,0,4,0,0,0
9,Chad,7.629853e+08,1.522646e+09,2.885400e+09,0.406,7.0,6.0,NF,22.0,960.440920,...,794.677933,0.108000,55.840891,111.438466,211.174845,0,4,0,0,0
10,Comoros,7.368316e+07,2.803613e+08,1.124295e+07,0.534,3.0,4.0,PF,26.0,1369.176631,...,723.357940,0.077000,97.029399,369.192814,14.805236,1,0,0,0,0
11,Congo,4.820413e+08,9.013684e+09,2.433887e+08,0.595,6.0,5.0,NF,23.0,3005.736912,...,1976.159875,0.100000,101.761441,1902.835892,51.380637,1,4,0,0,0
12,Cote D'Ivoire,1.815460e+09,2.865090e+09,1.851870e+09,0.478,5.0,4.0,PF,32.0,1377.796563,...,726.490656,0.071000,80.160942,126.506998,81.768633,1,0,0,0,0
13,Democratic Republic of Congo,5.359333e+09,1.356688e+09,6.982450e+09,0.441,6.0,6.0,NF,22.0,397.341671,...,-7.874582,0.108000,72.651738,18.391425,94.654899,0,0,0,0,0
14,Djibouti,1.897235e+08,7.788110e+07,4.741077e+08,0.475,6.0,5.0,NF,34.0,1595.150000,...,826.973923,0.114000,211.109741,86.660117,527.550675,0,0,0,2,0
15,Egypt,8.205844e+09,6.151464e+08,6.129272e+10,0.683,6.0,5.0,NF,37.0,2648.294169,...,1197.817927,0.072000,90.747858,6.802861,677.831989,0,0,0,0,0
16,Eritrea,4.860429e+08,4.853948e+08,1.028387e+09,0.436,7.0,7.0,NF,18.0,467.000000,...,158.866216,-0.071431,108.612937,108.468120,229.807076,0,4,0,0,0
17,Ethiopia,1.145084e+10,8.330864e+10,1.901191e+10,0.446,6.0,6.0,NF,33.0,449.420377,...,324.959577,0.163000,116.733003,849.271394,193.812700,1,3,1,0,0
19,Gambia,1.598891e+08,0.000000e+00,1.392312e+08,0.449,6.0,6.0,NF,29.0,747.708732,...,153.557089,0.067000,78.994956,0.000000,68.788680,0,4,0,0,0
20,Ghana,4.853869e+09,1.266398e+10,4.463691e+09,0.577,1.0,2.0,F,48.0,1626.622783,...,1368.151823,0.094000,178.290666,465.168975,163.958789,1,1,0,0,0
21,Guinea,6.315845e+08,9.247885e+08,1.347825e+09,0.446,5.0,5.0,PF,25.0,741.038135,...,377.555656,0.111000,56.639386,82.933402,120.870534,0,0,0,0,0
22,Guinea-Bissau,1.960218e+08,3.091138e+08,1.520517e+08,0.450,5.0,5.0,PF,19.0,555.605049,...,247.460929,-0.057431,115.822072,182.643988,89.841749,1,4,0,0,0
25,Jordan,1.829419e+09,1.578224e+08,2.581800e+10,0.720,6.0,5.0,NF,49.0,3353.623382,...,1678.798121,0.018000,205.090735,17.692999,2894.378653,0,4,0,4,0
26,Kenya,5.346269e+09,3.953264e+10,1.513368e+10,0.556,4.0,4.0,PF,25.0,1060.095016,...,662.612357,0.110000,114.481181,846.523638,324.061835,1,0,1,0,0
27,Lebanon,1.388968e+09,6.290871e+07,4.989869e+09,0.732,5.0,4.0,PF,27.0,6649.213772,...,2157.576513,0.224569,221.794562,10.045447,796.796976,0,0,0,2,0
28,Lesotho,3.305411e+08,2.453521e+08,1.388199e+09,0.493,2.0,3.0,F,49.0,1389.875532,...,953.387180,0.049000,161.757413,120.068365,679.345187,0,0,0,0,0
29,Liberia,9.805636e+08,6.930387e+08,4.512835e+09,0.464,3.0,4.0,PF,37.0,586.229361,...,279.396466,0.042000,224.925436,158.971888,1035.171491,0,0,0,2,0
30,Madagascar,2.249696e+09,1.650177e+08,2.095127e+09,0.512,4.0,4.0,PF,28.0,468.113001,...,222.173935,0.056000,95.366966,6.995274,88.814640,0,0,0,0,0
31,Malawi,1.771178e+09,1.028785e+09,4.089349e+09,0.472,3.0,4.0,PF,33.0,507.537975,...,351.152256,0.110000,108.731015,63.156175,251.041411,0,0,0,0,0
32,Mali,2.152685e+09,1.876385e+09,4.318933e+09,0.414,5.0,4.0,PF,32.0,706.981554,...,437.110416,0.106000,127.120385,110.804309,255.041747,0,0,0,0,0
33,Mauritania,5.270949e+08,1.220488e+09,6.745826e+08,0.518,6.0,5.0,NF,30.0,1369.187945,...,877.345183,0.072000,134.090267,310.485915,171.610380,1,4,0,0,0
35,Morocco,5.975941e+09,6.318299e+09,3.366876e+09,0.653,5.0,4.0,PF,39.0,3125.079481,...,1790.136430,0.122000,174.774221,184.786931,98.468710,1,0,0,0,0
36,Mozambique,3.848939e+09,7.052097e+09,8.185871e+09,0.420,4.0,3.0,PF,31.0,558.209344,...,244.641310,0.119000,146.424544,268.281734,311.413708,0,0,0,0,0
37,Namibia,1.583345e+07,2.942054e+09,2.659016e+09,0.631,2.0,2.0,F,49.0,6154.488886,...,4018.048643,0.088000,6.964562,1294.103684,1169.605220,1,1,0,0,0
38,Niger,1.594254e+09,1.783428e+09,1.784885e+09,0.353,3.0,4.0,PF,35.0,384.900656,...,226.195681,0.100000,82.860756,92.693030,92.768755,0,0,0,0,0
39,Nigeria,1.075609e+10,3.251860e+10,9.655779e+09,0.523,4.0,5.0,PF,27.0,2563.899969,...,1995.969233,0.015569,60.973878,184.340680,54.736455,1,3,1,0,0
40,Rwanda,2.101319e+09,3.305603e+09,3.652478e+09,0.513,6.0,6.0,NF,49.0,688.212199,...,469.532036,0.176000,189.587494,298.241806,329.537887,0,0,0,0,0
41,Sao Tome and Principe,5.515899e+07,0.000000e+00,3.884767e+07,0.577,2.0,2.0,F,42.0,1213.164082,...,150.674082,0.097000,281.815956,0.000000,198.478856,0,1,0,2,0
42,Senegal,2.227930e+09,2.037594e+09,3.656034e+09,0.501,2.0,2.0,F,43.0,1337.406690,...,732.752624,0.111000,157.176179,143.748325,257.926176,0,1,0,0,0
43,Sierra Leone,7.927226e+08,1.421289e+09,1.099909e+09,0.430,3.0,3.0,PF,31.0,567.834267,...,429.135575,0.132000,112.969412,202.545202,156.746025,1,0,0,0,0
44,South Africa,3.848384e+09,3.355333e+09,1.058959e+10,0.691,2.0,2.0,F,44.0,7582.696929,...,4550.269791,0.062000,70.553013,61.513827,194.140619,0,1,0,0,0
45,South Sudan,1.263369e+08,1.391514e+08,4.261786e+09,0.435,7.0,7.0,NF,15.0,831.850462,...,-8339.479683,-0.072431,11.969520,13.183603,403.773891,0,4,0,0,0
46,Swaziland,4.690000e+07,0.000000e+00,5.409131e+08,0.573,7.0,5.0,NF,43.0,4578.288570,...,2849.583235,0.105000,42.830229,0.000000,493.975048,0,0,0,0,0
47,Tanzania,7.763594e+09,2.410282e+10,9.664759e+09,0.509,3.0,3.0,PF,31.0,846.386841,...,435.434514,0.114000,155.396745,482.444055,193.450622,1,0,1,0,0
48,Togo,4.326932e+08,4.314954e+09,1.472300e+08,0.495,4.0,4.0,PF,29.0,611.535069,...,309.328675,0.069000,60.618296,604.504844,20.626228,1,0,0,0,0
49,Tunisia,3.714659e+09,1.355463e+08,1.054239e+09,0.728,1.0,3.0,F,40.0,4302.486544,...,2090.659727,0.075000,335.767137,12.251993,95.292374,0,0,0,2,0
50,Turkey,2.560656e+10,8.767650e+09,1.776648e+09,0.792,3.0,4.0,PF,45.0,13277.760770,...,8961.211862,0.137000,331.554180,113.523680,23.004070,1,0,3,2,0
51,Uganda,5.086029e+09,3.755668e+09,1.032902e+10,0.509,6.0,5.0,NF,26.0,676.337633,...,414.468635,0.114000,137.787414,101.746117,279.827034,0,0,0,0,0
52,Yemen,2.445064e+09,3.920571e+08,2.939501e+09,0.504,6.0,6.0,NF,19.0,1119.147493,...,564.698860,0.072000,94.683749,15.182190,113.830522,0,4,0,0,0
53,Zambia,1.604376e+09,9.288269e+09,6.452866e+09,0.565,3.0,4.0,PF,38.0,1644.106790,...,1298.417236,0.137000,104.181955,603.144023,419.024020,1,0,0,0,0
58,Palestine,0.000000e+00,2.011175e+07,1.336954e+10,0.682,6.0,6.0,NF,24.5,2603.521014,...,1127.349164,0.174569,0.000000,4.819035,3203.513553,0,0,0,4,0
59,Somalia,0.000000e+00,2.630742e+07,5.911542e+09,0.400,7.0,7.0,NF,8.0,486.080000,...,301.080000,0.100000,0.000000,1.959792,440.385023,0,4,0,0,0
60,Sudan,0.000000e+00,3.061064e+10,1.923096e+10,0.496,7.0,7.0,NF,11.0,1825.541037,...,1459.368229,0.093000,0.000000,806.017098,506.375568,1,4,1,0,0
61,Syria,0.000000e+00,1.796076e+08,3.572409e+09,0.551,7.0,7.0,NF,20.0,3300.000000,...,2122.370732,-0.039000,0.000000,9.596641,190.877966,0,4,0,0,0
63,Zimbabwe,0.000000e+00,2.333746e+10,3.928401e+09,0.537,5.0,6.0,NF,21.0,1232.864865,...,669.807124,0.085000,0.000000,1717.672202,289.136213,1,4,0,0,0

In [1203]:
# Looking at the countries in cluster 1
aid[aid['clusters_selected_features'] == 1]

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,pc_gdp_change,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid,cluster_pc_aid,clusters_selected_features
0,Algeria,4.380505e+08,5.880901e+08,2.476621e+08,0.749,6.0,5.0,NF,36.0,4702.091700,...,2937.203478,0.103,11.254086,15.108798,6.362761,1,6,0,0,1
18,Gabon,6.245637e+07,2.036791e+09,1.003941e+08,0.688,6.0,5.0,NF,37.0,9467.363786,...,5341.647122,0.061,33.154461,1081.213802,53.293411,1,6,0,0,1
23,Iran,1.605363e+09,0.000000e+00,6.386544e+07,0.788,6.0,6.0,NF,27.0,6236.289411,...,4566.279941,0.117,20.723515,0.000000,0.824435,0,6,0,0,1
24,Iraq,1.174182e+09,2.349945e+07,1.343100e+11,0.662,6.0,6.0,NF,16.0,5344.331964,...,4244.331964,0.054,34.121353,0.682886,3903.004400,0,8,2,4,1
54,Bahrain,0.000000e+00,1.815950e+07,9.002047e+08,0.810,7.0,6.0,NF,49.0,22395.306030,...,8758.909800,0.018,0.000000,13.591679,673.768118,0,5,0,0,1
55,Equatorial Guinea,0.000000e+00,3.762500e+09,5.080444e+06,0.590,7.0,7.0,NF,18.0,16130.336370,...,14404.781632,0.070,0.000000,3352.562039,4.526911,1,6,0,0,1
56,Israel,0.000000e+00,6.623150e+07,1.020541e+11,0.900,1.0,2.0,F,60.0,32977.960870,...,11934.385940,0.047,0.000000,8.061577,12421.839080,0,7,2,3,1
57,Libya,0.000000e+00,1.730100e+07,9.500085e+08,0.693,6.0,6.0,NF,18.0,6530.856715,...,-611.917737,-0.035,0.000000,2.719413,149.324577,0,6,0,0,1
62,United Arab Emirates,0.000000e+00,3.177106e+07,3.794542e+07,0.847,6.0,6.0,NF,70.0,38495.046350,...,5203.626980,0.065,0.000000,3.448064,4.118157,0,5,0,0,1
64,Kuwait,0.000000e+00,0.000000e+00,8.617661e+06,0.800,5.0,5.0,PF,44.0,37158.734200,...,18718.355680,0.014,0.000000,0.000000,2.334813,0,5,0,0,1
65,Oman,0.000000e+00,0.000000e+00,8.855178e+08,0.815,6.0,5.0,NF,45.0,16884.283410,...,8283.029240,0.111,0.000000,0.000000,219.880964,0,6,0,0,1
66,Qatar,0.000000e+00,0.000000e+00,1.885977e+07,0.854,6.0,5.0,NF,69.0,65560.375400,...,35584.258360,0.038,0.000000,0.000000,7.669075,0,2,0,0,1
67,Saudi Arabia,0.000000e+00,0.000000e+00,2.094263e+07,0.853,7.0,7.0,NF,49.0,21087.354410,...,11916.024265,0.109,0.000000,0.000000,0.677383,0,6,0,0,1

## Same Variables, But More Clusters

In [1204]:
# Instantiating my model. Trying true-k of 9 
true_k = 9
model = KMeans(n_clusters=true_k, init='k-means++', max_iter=100, n_init=1, random_state=22)
model.fit(X_scaled4)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=100,
       n_clusters=9, n_init=1, n_jobs=None, precompute_distances='auto',
       random_state=22, tol=0.0001, verbose=0)

In [1205]:
# Using my model to make predictions
model.predict(X_scaled4)

array([4, 7, 0, 5, 6, 6, 5, 6, 6, 6, 0, 6, 0, 6, 6, 6, 1, 8, 4, 6, 5, 6,
       1, 4, 1, 6, 7, 0, 0, 0, 6, 0, 6, 6, 3, 0, 0, 5, 0, 7, 6, 5, 0, 0,
       5, 1, 6, 0, 0, 0, 5, 6, 6, 0, 4, 4, 5, 1, 6, 6, 7, 1, 4, 7, 4, 4,
       2, 4], dtype=int32)

In [1206]:
# Making a column for new clusters
aid['clusters_selected_features_9'] = model.labels_
aid.head()

,country,world_bank_totals,chinese_aid_totals,usaid_aid,hdi_14,pr_score14,cl_score14,fh_status14,cpi_2014,gdp_per_cap14,...,hdi_change,world_bank_pc,chinese_aid_pc,usaid_pc,chinese_aid_total_max,clusters_all,cluster_all_aid,cluster_pc_aid,clusters_selected_features,clusters_selected_features_9
0,Algeria,4.380505e+08,5.880901e+08,2.476621e+08,0.749,6.0,5.0,NF,36.0,4702.091700,...,0.103,11.254086,15.108798,6.362761,1,6,0,0,1,4
1,Angola,8.030873e+08,3.864233e+10,2.939893e+09,0.557,6.0,5.0,NF,19.0,3843.198241,...,0.163,29.808251,1434.290317,109.120217,1,0,1,0,0,7
2,Benin,1.107820e+09,1.155924e+09,1.785451e+09,0.505,2.0,2.0,F,39.0,834.443596,...,0.107,107.692898,112.369168,173.566471,0,1,0,0,0,0
3,Botswana,3.858719e+08,2.563158e+09,2.141447e+09,0.709,3.0,2.0,F,63.0,7864.253281,...,0.131,184.750231,1227.205008,1025.295634,1,1,0,0,0,5
4,Burkina Faso,2.858288e+09,0.000000e+00,2.048434e+09,0.405,6.0,3.0,PF,38.0,639.708096,...,0.119,162.531851,0.000000,116.480855,0,0,0,0,0,6

In [1207]:
# Checking my silhouette score, which is good
silhouette_score(X_scaled4, model.labels_)

0.15932032443410982

In [1209]:
# Looking at the value counties of my clusters. Using Tableau to see the patterns. 
aid['clusters_selected_features_9'].value_counts()

6    21
0    16
4     9
5     8
1     6
7     5
8     1
3     1
2     1
Name: clusters_selected_features_9, dtype: int64

In [1208]:
# Saving my data to a csv 
aid.to_csv('./aid_data/combined_data/aid_clusters.csv', index=True)